### ISSUE TITLE
USe steam comands to launch the game instead, or have the option to

### ISSUE THREAD

**Issue by Scorch-Light** [project-curiosity/jackboxlauncher#2]

**Comment by project-curiosity** [comment]
I assume you mean launch the game with Steam launch options such as -fullscreen for example. I'm not sure how Steam functions but I assume as long as it is a steam game launching it using the game's exe will still launch the game with the Steam launch options. If that is not the case I am unsure that I can help you. I do not plan to and do not know how to launch the exe with steam launch options on my programs end. I'm not sure if this will help you but you can try follow these [steps](https://www.quora.com/How-do-you-add-launch-options-to-non-Steam-games) to add the steam launch options to a shortcut.

If I am misunderstanding your issue feel free to clarify and I will see if there is something I can do.
