### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by IceCreamGuy01** [project-curiosity/jackboxlauncher#4]
Whenever I click play jackbox opens on a white screen then closes about 2 seconds later. The only pack that works is #3 and it does not crash it works fine the other packs do not.

**Comment by project-curiosity** [comment]
I do not see why this would be happening for you specifically. It seems to work fine for me. I will be closing this issue but feel free to repost the issue with more information about how you are running the program and what platform you own each game on.

**Comment by csjjpm** [comment]
Hi, same issue for me.  Only game pack 3 games launch, for all of the other games flash up the main full game .exe for a second and disappear
